### ISSUE TITLE
A few questions about Jumi Actor implementation patterns

### ISSUE THREAD

**Issue by mttkay** [orfjackal/jumi-actors#3]
I'm creating an issue because there is no mailing list to discuss implementation questions--feel free to close this out if this isn't the appropriate channel.

I have a few questions around Actor APIs and implementations and appropriate use of jumi-actors in that context.

1. As far as I know, it is commonplace to include actor refs in messages passed to actors so they can communicate with other actors as continuations. In jumi-actors, I would have an `ActorRef` argument in one of the actor interfaces to do that. Now, if an Actor wants to pass itself as the continuation to another actor (to wait for a response to its request), how would you accomplish that, i.e. how do you obtain a self-reference from within an Actor interface impl? Or do you suggest to simply pass Actor refs to Actor constructors and hold strong references throughout the life time of an actor? How would you avoid cycles?
1. I noticed that in the Pi example, Actors use both `ActorThread` and the executor directly to spawn other Actors. Isn't exposing the scheduling mechanism (the `Executor` in this case) a smell, since it ties the Actor to a particular low level implementation for the concurrent computation?
1. What happens if you try to spawn more `ActorThread`s than the underlying thread pool provides threads? Since `ActorThreads` are basically message loopers and loop forever until they receive an interrupt, I suppose any actor thread created will wait in the `Executor` task queue forever? Have you thought about this case?

Thanks!

**Comment by orfjackal** [comment]
This channel is good for discussions, or you can also use the parent project's mailing list if you like: https://groups.google.com/forum/#!forum/jumi-test-runner

1) To obtain a self-reference, you would give the actor a reference to the `ActorThread` where that actor is running, after which it can call `ActorThread.bindActor` on itself. See for example https://github.com/orfjackal/jumi/blob/v0.5.437/jumi-core/src/main/java/fi/jumi/core/suite/SuiteRunner.java#L79

2) It uses `Executor` in order to execute the workers in parallel. An `ActorThread` is guaranteed to be backed by a single thread which never changes. This is a deliberate design decision in order to give the programmer full control of in which thread things are executed, because this was developed for the needs of the Jumi Test Runner. Many other actor libraries take a different approach.

3) The backing `Executor` must create new threads instead of waiting for existing threads to stop. In practise you always must use `Executors.newCachedThreadPool()` or a similar pool. `MultiThreadedActors` could have been implemented so that it takes a `ThreadFactory` instead of `Executor`, but I considered executors more convenient to use because of their shutdown operations.

**Comment by mttkay** [comment]
Thanks for getting back to me.

> To obtain a self-reference, you would give the actor a reference to the ActorThread where that actor is running, after which it can call ActorThread.bindActor

Ah ok--so are you saying calling `bindActor` multiple times is a safe thing to do? Since other actors might need a reference to the actor, I would end up calling it twice: once "outside" the Actor class, and once more inside the actor when it needs to pass itself to another actor as a continuation.

> The backing Executor must create new threads instead of waiting for existing threads to stop. In practise you always must use Executors.newCachedThreadPool() or a similar pool.

So there is a chance that if an Actor blocks / hangs, I will end up creating an unbounded number of threads? I'm just cautious around this as I was planning to use the library on Android/mobile where resources are more constrained (I would usually never create an unbounded thread pool)

**Comment by orfjackal** [comment]
Yes, just call `bindActor` as many times as you wish. It just instantiates a dynamic proxy and a couple cheap objects which wrap a strong reference to the actual actor object and its actor thread.

A new thread is started only when you call `Actors.startActorThread()`, so you are in full control of how many threads there are. So it is perfect for mobile use. ;)

**Comment by mttkay** [comment]
Great, thanks for clarifying!
